name: Crunchy CI
on: [push, pull_request]

jobs:
  test-coverage:
    name: Test Crunchy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:

    - name: Git checkout
      uses: actions/checkout@v2.5.0

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install

    - name: Get Conda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        auto-update-conda: true

    # Need to add shell to make conda environments work
    - name: Install spring
      shell: bash -l {0}
      run: |
        conda install -c bioconda spring

    - name: Install samtools
      shell: bash -l {0}
      run: |
        conda install -c bioconda samtools

    - name: Unit tests and coverage
      run: |
        poetry run pytest --cov=./ --cov-report xml --cov-report term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests