name: Build
on: [push, pull_request]

jobs:
  build:
    name: Test Crunchy (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:

    - name: Git checkout
      uses: actions/checkout@v1

    - name: Get Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    # Need to add shell to make conda environments work
    - name: Install spring
      shell: bash -l {0}
      run: |
        conda install -c bioconda spring

    - name: Install samtools
      shell: bash -l {0}
      run: |
        conda install -c bioconda samtools

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python setup.py install

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pip install pytest
        pip install pytest-mock
        py.test -rxs tests/