name: Python Master Workflow
on: 
  push:
    branches:
      - 'master'

jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        python-version: [3.7]
    
    steps:
    
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Get Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    # Need to add shell to make conda environments work
    - name: Install spring
      shell: bash -l {0}
      run: |
        conda install -c bioconda spring
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    
    - name: Generate coverage report
      shell: bash -l {0}
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: .coverage.xml
        flags: unittests
  
  